### ISSUE TITLE
Set up mig

### ISSUE THREAD

**Issue by mgreensmith** [mozilla-itcloud/mdn-migration-project#16]
Copied from gdoc. Need info on this.

**Comment by jwhitlock** [comment]
The Mozilla InvestiGator (MIG) is Mozilla's real-time digital forensics and investigation platform.

* https://mig.mozilla.org/
* https://github.com/mozilla/mig/

It is deployed as a [Daemonset](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/) on each node in the cluster.

**Comment by mgreensmith** [comment]
We already run mig on the k8s host, so this requirement is deprecated.
