### ISSUE TITLE
Set up IP autoblocker

### ISSUE THREAD

**Issue by mgreensmith** [mozilla-itcloud/mdn-migration-project#18]
There's a script somewhere that scrapes logs for misbeahving users and adds them to a block list (ACL?) This functionality needs to be implemented.

**Comment by jwhitlock** [comment]
It's currently in the MDN secrets repo, in the utils folder. We should evaluate if it can be turned into a public project, so that we don't need to be vague about how it works.

**Comment by mgreensmith** [comment]
It can be pointed at ELK with some light dev work.

**Comment by jeffbryner** [comment]
we should consider either sending these logs to mozdef and having it do the correlation, or sending the output of the block to mozdef such that we can protect more than just MDN. The AWS site for MDN should also consume the current blocklist mozdef produces as it's correlated from all sites mozdef has logs for.
