### ISSUE TITLE
Refactor terraform infra code

### ISSUE THREAD

**Issue by mgreensmith** [mozilla-itcloud/mdn-migration-project#2]
Goal: to remove the need for `make` tasks, shell scripts, or manual co-ordination required to deploy the supporting AWS infrastructure (out-of-k8s-cluster components only) needed to host MDN.

### Tasks
- [ ] Re-implement [1] and [2] to unblock Ryan Johnson's ability to deploy k8s resources.
- [ ] Re-implement all remaining tf resources.

[1] https://github.com/mdn/infra/blob/master/apps/mdn/mdn-aws/infra/shared/provision.sh
[2] https://github.com/mdn/infra/blob/master/apps/mdn/mdn-aws/infra/multi_region/portland/provision.sh

**Comment by mgreensmith** [comment]
Infra setup notes from metadave: https://gist.github.com/metadave/0cdc9b525ecec678a6b482189db4f363

**Comment by limed** [comment]
WIP: https://github.com/limed/infra/tree/mdn-refactor

**Comment by mgreensmith** [comment]
Are existing terraform resources still being deployed from mozmeao/infra, or are we deploying current prod infra from mdn/infra? If the former, would there be any other reason why we're blocked on merging https://github.com/mdn/infra/pull/4

**Comment by escattone** [comment]
@mgreensmith No, we're not deploying any new Terraform resources using this code. We are deploying the current stage and production instances of MDN from the code under `apps/mdn/mdn-aws/k8s`, but mdn/infra#4 doesn't touch that code. So I think there's no reason we're blocked on  mdn/infra#4 other than a review from @metadave and myself! 😄

**Comment by mgreensmith** [comment]
Merge via #31
