### ISSUE TITLE
Cutover plan

### ISSUE THREAD

**Issue by mgreensmith** [mozilla-itcloud/mdn-migration-project#20]
There are some unknowns about moving the CloudFront distro to our account.

**Comment by mgreensmith** [comment]
`developer.mozilla.org` is on infoblox, is a CNAME to `mdn-prod.moz.works`, which is a CNAME to a MozMEAO cloudfront distro.

Cloudfront needs to know that it fronts `developer.mozilla.org`. This name can only exist on one cloudfront distro. Our best understanding is that it can take up to a day for cloudfront to recognize that it no longer handles a specific fronting domain\, which means we must detach the CDN at least a day before cutover. (this data could be outdated)

25% of requests are handled by the CDN, 75% make it to the backend.

We can go live without a CDN, for improved debugging capability, and then add our own cloudfront distro a day or so later.

**Comment by jwhitlock** [comment]
I thought about this some more, and I'm not as confident in my 25%/75% estimate. 

We [moved developer.mozilla.org to a CDN](https://hacks.mozilla.org/2018/05/cdn-bcd-and-svg-mdn-changelog-for-april-2018/#cdn-apr-18) in April. Before this, static assets were served from a CDN, but the HTML requests went to Django. After the change, CloudFront had a chance to serve the initial page from cache (with a low 5-minute timeout) and the assets were served from developer.mozilla.org as well.

It is possible that the assets are a significant portion of the CDN traffic, and we'd need more than a 25% boost in nodes to handle the additional traffic.

If others think this traffic will be significant, we could try splitting the traffic again, sending assets traffic to a different domain name, handled by CloudFront with an origin in the new cluster. We'll then be back to the 25% increase in traffic when dropping the CDN. We can re-combine when the developer.mozilla.org CDN points to the new datacenter

Another option is [Fastly](https://www.fastly.com/), which wants to give MDN free CDN service, and might be a better fit than CloudFront. This may help reduce the time where the host is not covered by a CDN.

**Comment by limed** [comment]
Moved to mdn/infra#43
