### ISSUE TITLE
Deploy k8s services to staging cluster

### ISSUE THREAD

**Issue by mgreensmith** [mozilla-itcloud/mdn-migration-project#27]

**Comment by escattone** [comment]
All of the following K8s resources have been successfully deployed:
- the "web", "api" and "kumascript"  Services
- the "mdn-s3-sync-stage" CronJob
- the "mdn-backup-secrets", "mdn-secrets", and "newrelic-secrets" Secrets
- the "mdn-shared-stage" PersistentVolume
- the "mdn-shared" PersistentVolumeClaim
- the "api", "web", "kumascript", "celery-beat", "celery-cam", and "celery-worker" Deployments

I also manually updated the following DNS entries to point to the new ELB created for the "web" K8s Service
- stage.mozilla-mdn.nubis.allizom.org
- files.mozilla-mdn.nubis.allizom.org

I think we should increase the number of worker (non-master) nodes within the cluster, currently two (2). We have ten (10) worker nodes within the MoMEAO cluster that are shared between the stage and production deployments. When I started a large indexing task (index all 50k+ documents), some of the pods started to fail their health checks and were continually restarted.
