### ISSUE TITLE
Sync S3 buckets into staging

### ISSUE THREAD

**Issue by mgreensmith** [mozilla-itcloud/mdn-migration-project#28]
- [ ] Attachments bucket
- [ ] Legacy files bucket

**Comment by escattone** [comment]
• Added policy to the "mdn-shared-backup" bucket in the MozMEAO account that gives the MDN IT account read access to MozMEAO's "mdn-shared-backup" S3 bucket.
• Ran the following sync command using my MDN IT credentials:
aws-vault exec --assume-role-ttl 1h mozilla-mdn-admin -- aws s3 sync --exclude "logs/*" s3://mdn-shared-backup s3://mdn-shared-backup-8c8641b943fc3a0f

**Comment by escattone** [comment]
I also manually created an "mdn-efs-backup" programmatic-access-only user (with associated policy with the same name) within the MDN IT AWS account. This user has read/write permission for any s3 buckets named "mdn-shared-backup-*", and its access keys are used by the "mdn-s3-sync-stage" K8s CronJob resource (via the "mdn-backup-secrets" Secrets K8s resource) for sync'ing the data (attachments and legacy files) from the S3 bucket into the EFS instance. This has been running successfully for two days now.
