### ISSUE TITLE
Set-up Cron Job Monitoring

### ISSUE THREAD

**Issue by escattone** [mozilla-itcloud/mdn-migration-project#39]
MDN is currently using Dead Man's Snitch to monitor cron jobs, for example the three K8s CronJob's, "mdn-backup-prod" in production, "mdn-s3-sync-stage" in stage, and "mdn-restore-prod" in the standby cluster. Marketing owns and pays for this Dead Man's Snitch account.

We need to either create a new IT-owned Dead Man's Snitch account and use it for the new stage, production, and standby instances, or determine an equivalent approach.

**Comment by limed** [comment]
We have deamanssnitch created
