### ISSUE TITLE
Relocate MDN infra codebase

### ISSUE THREAD

**Issue by mgreensmith** [mozilla-itcloud/mdn-migration-project#7]
Tracked in https://github.com/mdn/sprints/issues/148

**Comment by jwhitlock** [comment]
This is complete:

* [mdn/infra](https://github.com/mdn/infra) is used for:
  - Kubernetes application configuration
  - Deployments using MozMEAO CI
  - Terraform for the IT cluster
* [mozmeao/infra](https://github.com/mozmeao/infra) is used for:
  - Terraform for MozMEAO clusters
  - Other in-use MozMEAO configuration

We'll keep some of MDN in the MozMEAO repository until the clusters are decommissioned.
